using SandBox.GauntletUI.AutoGenerated1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;
using TaleWorlds.Localization;
using TaleWorlds.MountAndBlade;

namespace RealmsForgotten.Career.Ability
{
    public class ClassAbility
    {
        private int _coolDownLeft = 0;
        private Timer _timer = null;
        private float _cooldown_end_time;
        private bool _isLocked;

        public int GetCoolDownLeft() => _coolDownLeft;
        public ClassAbility()
        {
            //StringID = template.StringID;
            //Template = template;
            _timer = new Timer(1000);
            _timer.Elapsed += TimerElapsed;
            _timer.Enabled = false;

        }
        private void TimerElapsed(object sender, ElapsedEventArgs e)
        {
            if (Mission.Current == null)
            {
                FinalizeTimer();
                return;
            }

            _coolDownLeft = (int)(_cooldown_end_time - Mission.Current.CurrentTime);
            if (_coolDownLeft <= 0)
            {
                FinalizeTimer();
            }
        }
        private void FinalizeTimer()
        {
            _coolDownLeft = 0;
            _timer.Stop();
        }


        public bool IsDisabled(Agent casterAgent, out TextObject disabledReason)
        {
            disabledReason = new TextObject("{=!}Enabled");
            if (IsOnCooldown())
            {
                disabledReason = new TextObject("{=!}On cooldown");
                return true;
            }
            if (_isLocked)
            {
                disabledReason = new TextObject("{=!}Mission is over");
                return true;
            }
            return false;
        }
        public void SetCoolDown(int cooldownTime)
        {
            _coolDownLeft = cooldownTime;
            _cooldown_end_time = Mission.Current.CurrentTime + _coolDownLeft + 0.8f; //Adjustment was needed for natural tick on UI
            _timer.Start();
        }
        public bool IsOnCooldown() => _timer.Enabled;
        public virtual bool CanCast(Agent casterAgent, out TextObject failureReason)
        {
            if (IsDisabled(casterAgent, out failureReason))
            {
                return false;
            }
            if (!casterAgent.IsActive() || casterAgent.Health <= 0)
            {
                failureReason = new TextObject("Caster is dead or routed");
                return false;
            }
            failureReason = null;
            return true;
        }

        public bool TryCast(Agent casterAgent, out TextObject failureReason)
        {
            if (CanCast(casterAgent, out failureReason))
            {
                DoCast(casterAgent);
                failureReason = null;
                return true;
            }
            return false;
        }
        protected virtual void DoCast(Agent casterAgent)
        {
            //OnCastStart?.Invoke(this);
            ActivateAbility(casterAgent);
        }

        private void ActivateAbility(Agent casterAgent)
        {
            SetCoolDown(15);
        }
        public static ClassAbility GetPlayersAbility()
        {
            return null;
        }
    }
}
