using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace RealmsForgotten.AiMade
{
    public class QuestMapNotification : InformationData
    {
        public override TextObject TitleText => new TextObject("{=YourTextId}Quest Alert");

        public override string SoundEventPath => "event:/ui/notification/quest_alert";

        [SaveableProperty(1)]
        public Hero QuestGiver { get; private set; }

        public QuestMapNotification(Hero questGiver, TextObject descriptionText)
            : base(descriptionText)
        {
            QuestGiver = questGiver;
        }

        protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
            base.AutoGeneratedInstanceCollectObjects(collectedObjects);
            collectedObjects.Add(QuestGiver);
        }
    }
}